spring:
  profiles:
    active:
      - dev

---
web-service:
  url: 127.0.0.1:9001
server:
  port: 9000
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 30000
  proxy:
    addProxyHeaders: true
  routes:
    oc:
      path: /oc/**
      url: http://192.168.10.126:9001/oc
    jjd:
      path: /jjd/**
      url: http://192.168.10.126:9003/jjd
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 10000
  endpoints:
    web:
      exposure:
        include: "*"

---

# web-service:
#   url: 127.0.0.1:9001
# server:
#  port: 9000
# spring:
#  profiles: test
#  application:
#   name: microservicecloud-config-client
# zuul:
#   host:
#     socket-timeout-millis: 60000
#     connect-timeout-millis: 30000
#   proxy:
#     addProxyHeaders: true
#   routes:
#     oc:
#       path: /oc/**
#       url: http://192.168.10.126:9001/oc
#    jjd:
#       path: /jjd/**
#       url: http://192.168.10.126:9003/jjd
